config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {registrations: "registrations"}
  resources :otos
  resources :search

  devise_scope :user do
      get "login", to: "devise/sessions#new"
      get "signup", to: "devise/registrations#new"
      get "logout", to: "devise/sessions#destroy"
  end

  authenticated :user do
       root "otos#profile"
       get "profile", to: "otos#profile"
  end

  root "index#welcome"
  get "license/terms"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oto.rb
class Oto < ApplicationRecord
     belongs_to :user
     has_attached_file :image, styles: { medium: "700x500#", small: "350x200#" }, default_url: "/images/:style/missing.png"
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
     validate :oto_count_within_limit, :on => :create
     validates_attachment_size :image, :in => 0.megabytes..10.megabytes
     attr_accessor :validation_code, :flash_notice

     def self.search(search)
          if search
               where("zipcode LIKE ?", "%#{search}%")
          else
               all
          end
     end

     def oto_count_within_limit
          if self.user.otos.count >= 25
               self.errors.add(:base, "Exceeded Otos Limit")
          end
     end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lockable
  validates_uniqueness_of :name
  validates_uniqueness_of :bio
  validates_uniqueness_of :email
  has_many :otos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     protect_from_forgery with: :exception
     before_action :configure_permitted_parameters, if: :devise_controller?

     def authorized_pilot
          redirect_to root_url, alert: "You are not a photographer. This page is denied to you." if current_user.pilot == false
     end

     protected
          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
               devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
               devise_parameter_sanitizer.permit(:sign_up, keys: [:bio])
               devise_parameter_sanitizer.permit(:sign_in, keys: [:bio])
               devise_parameter_sanitizer.permit(:sign_up, keys: [:camera])
               devise_parameter_sanitizer.permit(:sign_in, keys: [:camera])
               devise_parameter_sanitizer.permit(:sign_up, keys: [:priceph])
               devise_parameter_sanitizer.permit(:sign_in, keys: [:priceph])
               devise_parameter_sanitizer.permit(:sign_up, keys: [:airtime])
               devise_parameter_sanitizer.permit(:sign_in, keys: [:airtime])
               devise_parameter_sanitizer.permit(:sign_up, keys: [:zipcode])
               devise_parameter_sanitizer.permit(:sign_in, keys: [:zipcode])

               devise_parameter_sanitizer.permit(:sign_up) do |user_params|
                    user_params.permit(:name, :email, :bio, :camera, :priceph, :airtime, :zipcode, :password, :password_confirmation)
               end

               devise_parameter_sanitizer.permit(:account_update) do |user_params|
                    user_params.permit(:name, :bio, :camera, :priceph, :airtime, :zipcode, :current_password, :preferred)
               end
          end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def welcome
  end
end

app/controllers/license_controller.rb
class LicenseController < ApplicationController
     def terms
     end
end

app/controllers/otos_controller.rb
class OtosController < ApplicationController
     before_action :find_oto, only: [:show, :edit, :update, :destroy]
     before_action :authenticate_user_first, only: [:edit, :update, :destroy]
     before_action :authorized_pilot, only: [:edit, :update, :destroy, :profile]

     def index
          @otos = Oto.all.order("created_at ASC")
          @otos = Oto.search(params[:search])
     end

     def new
          @oto = current_user.otos.build
     end

     def create
          @oto = current_user.otos.build(oto_params)
          if @oto.save
               redirect_to @oto
          else
               alert = @oto.errors.full_messages_for(:base).to_sentence
               render "new"
          end
     end

     def profile
          @otos = Oto.where(user_id: current_user)
     end

     def show
     end

     def edit
     end

     def update
          if @oto.update(oto_params)
               redirect_to @oto
          else
               render "edit"
          end
     end

     def destroy
          if @oto.destroy
               redirect_to root_path
          else
               redirect_to @oto
          end
     end

     private
          def oto_params
               params.require(:oto).permit(:title, :description, :image).merge(zipcode: current_user.zipcode)
          end

          def find_oto
               @oto = Oto.find(params[:id])
          end

          def authenticate_user_first
               if current_user != Oto.find(params[:id]).user
                    redirect_to @oto
               else
               end
          end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
     prepend_before_action :check_captcha, only: [:create]

     private
          def check_captcha
               unless verify_recaptcha
                    self.resource = resource_class.new sign_up_params
                    respond_with_navigational(resource) { render :new }
               end
          end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/license_helper.rb
module LicenseHelper
end

app/helpers/otos_helper.rb
module OtosHelper
end

app/views/index/welcome.html.haml
.banner
     #footage
          = video_tag("skotoIntroVideo.mp4", :controls => false, :autobuffer => true, :autoplay => true, :loop => true, :preload => "auto", id: "heroVideo")

.wrapper
     #header
          %h1
               %span High res photos and videos for just about anything. Now doesn't that sound lovely?
          #links
               = link_to "Sign Up", new_user_registration_path, class: "button"
               = link_to "Start Hiring", otos_path, class: "button"
     #forWhom
          %h1
               %span So, who is Skoto for?
          #bubbles
               .bubble
                    .wrapper
                         %h3 We're for aerial photographers...
                         %p This could be a new job for aerial photographers. Paying only $5 per month, photographers can upload 25 photos and videos on their account. In return, they get noticed by the world and they can market their skills to anyone skeeing a unique perspective on their event.
                         = link_to "Sign Up", new_user_registration_path, class: "button"
               .bubble
                    .wrapper
                         %h3 We're for everyone else...
                         %p Anyone can browse the hundreds of photos and videos people had uploaded. If someone likes the style that the photographer provides, with a few clicks, they can meet together for a project. When they're done, they photographer gets paid and the person gets the service.
                         = link_to "Start Hiring", otos_path, class: "button"
     #nutshell
          %h1
               %span In a Nutshell...
          %p Let's say Jane Doe is an aerial photographer. She hears about Skoto and thinks, "This is perfect!" She reads what it's about and signs up immediately. She pays only $5 per month. She thinks to herself how cheap that is. She starts uploading aerial photos and videos of her landscape. She knows that she can only upload 25 of either thing.
          %p Now imagine Shia Labeouf needed an aerial video of his wedding. He loves Jane's photos and gets her contact info directly from Skoto. They meet and Shia asks Jane if she is willing to take a video of the wedding. Jane agrees. During the wedding, Jane takes beautiful photos and videos of the wedding.
          %p Shia Labeouf pays Jane her amount she specified on her profile. They thank each other and walk away both happy. Now doesn't that sound awesome?
     #cta
          %h1
               %span Well? What are you waiting for?!
          %p
               Start uploading aerial photos and videos or start hiring.
               %br
               It's a win-win either way.
          = link_to "Sign Up", new_user_registration_path, class: "button"
          = link_to "Start Hiring", otos_path, class: "button"
     #footer
          %h1
               %span Skoto is Copyright (c) 2017 by Peter G and Brehanu B
          %p
               All rights reserved |
               = link_to "Terms and Conditions", otos_path
          %p
               Read our
               = link_to "blog", otos_path
          %p
               Contact Us
               = link_to "admin@skoto.co", "mailto:admin@skoto.co"

app/views/layouts/application.html.haml
!!!
%html
%head
     %title Skoto
     = csrf_meta_tags
     = stylesheet_link_tag "application", media: "all"
     = javascript_include_tag "application"
     %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}
     %link{:href => "https://fonts.googleapis.com/css?family=Poppins:500,700", :rel => "stylesheet"}/
     = favicon_link_tag "/images/favicon-32.ico"
     %meta{"title" => "Content-Type", :content => "Skoto LLC"}/
     %meta{"description" => "Content-Type", :content => "High res aerial photos for just about anything and a opportunity for photographers can make a living taking photos"}/
     %meta{"keywords" => "Content-Type", :content => "aerial, photos, photo, aerial photos, aerial photo, photographer, photographers, skoto, skoto llc"}/
     %meta{"viewport" => "Content-Type", :content => "width=device-width, initial-scale=1.0"}/
     %meta{"author" => "Content-Type", :content => "Skoto LLC - Peter G and Brehanu B"}/
     %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
     %script{:src => "https://www.google.com/recaptcha/api.js"}
%body
     %span.line
     .navigation
          .wrapper
               = link_to raw("<i class='fa fa-bars'></i>"), "#", id: "navToggle"
               #menu
                    .wrapper
                         #menuItems
                              = link_to raw("<i class='fa fa-times'></i>"), "#", id: "closeNav"
                              %ul
                                   - if user_signed_in?
                                        %li
                                             %i.fa.fa-camera.nav
                                             = link_to "Browse Photos", otos_path
                                        %li
                                             %i.fa.fa-user.nav
                                             = link_to "View Your Profile", profile_path
                                        %li
                                             %i.fa.fa-pencil.nav
                                             = link_to "Edit Your Account", edit_user_registration_path
                                        %li
                                             %i.fa.fa-sign-out.nav
                                             = link_to "Log Out", destroy_user_session_path, method: :delete
                                   - else
                                        %li
                                             %i.fa.fa-home.nav
                                             = link_to "Home", root_path
                                        %li
                                             %i.fa.fa-camera.nav
                                             = link_to "Scan Photos / Videos", otos_path
                                        %li
                                             %i.fa.fa-key.nav
                                             = link_to "Log In", new_user_session_path
                                        %li
                                             %i.fa.fa-sign-in.nav
                                             = link_to "Sign Up", new_user_registration_path
                              %ul#second
                                   %li
                                        %i.fa.fa-gavel.nav
                                        = link_to "Terms and Conditions", license_terms_path
                                   %li
                                        %i.fa.fa-plane.nav
                                        = link_to "Know Before You Fly", "http://knowbeforeyoufly.org/", :target => "_blank"
                                        %p FAA Rules and Regulations
                                   %li
                                        %i.fa.fa-rss.nav
                                        = link_to "Read Blog", otos_path
     .container
          - if alert
               #alert
                    .fontawesome
                         %i.fa.fa-exclamation-triangle
                    %p.alert= alert
          - if notice
               #notice
                    .fontawesome
                         %i.fa.fa-check
                    %p.notice= notice
          = yield

app/views/license/terms.html.haml
.wrapper
     #header.license
          %h1 Terms and Agreements
          %p Blah. Blah. Blah.

app/views/otos/_form.html.haml
.wrapper
     #otoForm
          = simple_form_for @oto do |f|
               = f.input :image, class: "image", label: false
               = f.input :title, class: "title", label: false, placeholder: "Photograph Title"
               = f.input :description, class: "description", label: false, placeholder: "Brief Description (Where'd you take it? What is it? Are you proud of it? What aperture did you use?)"
               = f.button :submit, value: "Upload", class: "button", label: false

app/views/otos/edit.html.haml
.wrapper
     #header.license
          %h1 
               %span Edit your Aerial Photograph
          %p
               Upload a image/video/gif that is of an aerial shot
               %br
               Asset must be appropriate and aerial in some way

= render "form"

app/views/otos/index.html.haml
- if @quota_warning.present?
     %span= @quota_warning


.banner
     #footage
          = image_tag("anders.jpg")
     #search
          .wrapper
               %h1 
                    %span Hello There
               %p
                    Discover the newest aerial photos
                    %br
                    and aerial videos below
               = form_tag(otos_path, :method => "get", id: "search-form") do
                    = text_field_tag :search, params[:search], placeholder: "ZIP Code"
                    %br
                    = submit_tag "Search", :name => nil, class: "button"

.wrapper
     #header
          %h1 
               %span Aerial Galore!
          #loop
               - @otos.each do |oto|
                    .photo
                         = link_to (image_tag oto.image.url(:small)), oto
                         %h1= link_to oto.title, oto
                         %p
                              %b Photographer -
                              = oto.user.name
                         %p
                              %b Charges Per Hour -
                              = oto.user.priceph

app/views/otos/new.html.haml
.wrapper
     - if @oto.errors[:base].any?
          #alert
               .fontawesome
                    %i.fa.fa-exclamation-triangle
               %p.alert= @oto.errors.full_messages_for(:base).to_sentence
     #header.license
          %h1 
               %span Upload a Aerial Photograph
          %p
               Upload a image/video/gif that is of an aerial shot
               %br
               Asset must be appropriate and aerial in some way

= render "form"

app/views/otos/profile.html.haml
.wrapper
	#header.profile
		%h1
			%span Hello
			%span= current_user.name
		= link_to "New Post", new_oto_path, class: "button"
	#loop
		- @otos.each do |oto|
			.photo
				= link_to (image_tag oto.image.url(:small)), oto
				%h1= link_to oto.title, oto
				%p
					%b Photographer -
					= oto.user.name
				%p
					%b Charges Per Hour -
					= oto.user.priceph

app/views/otos/show.html.haml
.banner
     #footage
          = image_tag @oto.image

.wrapper
     #header
          %h1
               %span= @oto.title
               by
               %span= @oto.user.name
          %p= simple_format(@oto.description)
          #links
               - if @oto.user == current_user
                    = link_to "Back", :back, class: "button"
                    = link_to "Contact Info", "#", class: "button", id: "contact"
                    = link_to "Edit", edit_oto_path, class: "button"
                    = link_to "Delete Footage", @oto, method: :delete, data: { confirm: "Are you sure you want to delete " + @oto.title + "? This action is irreversible." }, class: "button"
               - else
                    = link_to "Back", :back, class: "button"
                    = link_to "Contact Info", "#", class: "button", id: "contact"

#contactInfo
     .wrapper
          #text
               = link_to raw("<i class='fa fa-times'></i>"), "#", id: "closeInfo"
               %ul
                    %li
                         %i.fa.fa-user
                         = @oto.user.name
                    %li
                         %i.fa.fa-envelope
                         = link_to @oto.user.email, "mailto:" + @oto.user.email, id: "lowercase"
                    %li
                         %i.fa.fa-address-book
                         = @oto.user.bio
                    %li
                         %i.fa.fa-camera
                         = @oto.user.camera
                    %li
                         %i.fa.fa-clock-o
                         = @oto.user.airtime
                    %li
                         %i.fa.fa-credit-card-alt
                         = @oto.user.priceph
                    %li
                         %i.fa.fa-map-pin
                         = @oto.user.zipcode